### ISSUE TITLE
Pair: [Rachel and Chenxin]: design website in presentation and implement in HTML

### ISSUE THREAD

**Issue by maggie3000** [rkwreck/team_giraffe_website#17]

**Comment by chenxin-chex** [comment]
![Design](https://user-images.githubusercontent.com/55467785/133028043-812038b4-41c8-4469-98f6-7b93c9dabaf2.PNG)

**Comment by chenxin-chex** [comment]
Wireframe design presentation: https://docs.google.com/presentation/d/1KXoJSfJb9RgJG3XHu-xgxZIKMPKaZzQIq304UxX876s/edit?usp=sharing
