### ISSUE TITLE
Groom Scrum Board and Timebox Readme Week 5

### ISSUE THREAD

**Issue by chenxin-chex** [rkwreck/team_giraffe_website#39]

**Comment by jm1021** [comment]
README looks great, thank for adding link above.   Breakdown looks good.  Perhaps checkboxes instead of numbers.

**Comment by jm1021** [comment]
README is strong, journals look good.  I like the layout style with Padlets and positive and negatives shown.  Rachel, Chenxin, Rini were easy to see progress and notes.  Maggie looks to be a little behind.  

BTW, when you don't know how to start on something be sure to ask.
