### ISSUE TITLE
N@tM Presentation Review Ticket

### ISSUE THREAD

**Issue by chenxin-chex** [rkwreck/team_giraffe_website#51]

**Comment by calebkimsd** [comment]
we enjoy the "About Us" page where you can interact with the website. The wireframe and the overall aesthetic of the giarafee are very nice. I like the stocks that are present - but a feature needed is on-time data (stocks). AMC moonn

**Comment by mistylavender** [comment]
I like how you incorporated all the minilabs into different parts of your website and made the table out of information off yahoo. your presentation looks well and used an interesting idea for the website. well done!

**Comment by yajatyadav** [comment]
I liked the stocks system that you implemented. One thing I would recommend is adding more options to sort the stocks, such as by name, percent increase, rank, etc.

**Comment by jli615** [comment]
I really liked how you have pages that show everyone's individual work, and I like how clean the website looks. You could improve this by using an API instead of manually updating the page

**Comment by iBraskyy** [comment]
Good job guys! Formatting looked great. I also thought your guys' RGB and greyscale lab looked great. Overall theme of colors is great and it's awesome you're doing something on stocks.

**Comment by Uhpachee** [comment]
The frontend is very clean and the use of styles helps a lot to make it look nice. The color scheme is very nice as well. The giraffe theme was also very nice.

**Comment by iskapoor** [comment]
The page was personalized and full of detailing (like the button effects). It's formated well with an intriguing color palate. Wonderful job!

**Comment by chenxin-chex** [comment]
Highlights and improvements: students liked our color scheme and button transitions. Some suggestions are to use Web API to automatically update Stocks, and use filters to organize the page.
