### ISSUE TITLE
Individual Final - Rachel

### ISSUE THREAD

**Issue by chenxin-chex** [rkwreck/team_giraffe_website#53]

**Comment by jm1021** [comment]
Focus was CB questions in relationship to class mini labs.  Well prepared.  Lots of relationships between quiz and mini labs.  Good visuals.   Great knowledge exhibited.  I was glad to see Controller and Model style examples as it added to variety.

I would have liked to see something from the team PBL project.  5.5/6.0, comments could be more direct with concrete suggestions.  1.75/2
